modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/MasterAbdoTGM50/Mankini/issues"
license="MIT"

[[mods]]
modId="mankini"
version="${file.jarVersion}"
displayName="Mankini"
displayURL="https://minecraft.curseforge.com/projects/mankini"
authors="MasterAbdoTGM50, Kara2810, Mrbysco"
credits="Runew0lf, Geekasaurus"
description='''
A minecraft mod allowing you to become a mankini wearing star. What would you ask for more?
'''
[[dependencies.mankini]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"