modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/MasterAbdoTGM50/Mankini/issues"
license="MIT"

[[mods]]
modId="mankini"
version="${file.jarVersion}"
displayName="Mankini"
displayURL="https://minecraft.curseforge.com/projects/mankini"
authors="MasterAbdoTGM50, Kara2810, Mrbysco"
credits="Runew0lf, Geekasaurus"
description='''
A minecraft mod allowing you to become a mankini wearing star. What would you ask for more?
'''
[[dependencies.mankini]]
modId="minecraft"
type="required"
versionRange="[1.21.7,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.mankini]]
modId="neoforge"
type="required"
versionRange="[21.7.0-beta,)"
ordering="NONE"
side="BOTH"